### ISSUE TITLE
potential for multiple instances of docker image

### ISSUE THREAD

**Issue by aledj2** [moka-guys/dnanexus_tso500_output_parser#6]
If a run is split into multiple jobs it'd be good for this app to be able to run a selection of tasks. eg one output parser run per docker image, but excluding multiqc and then finally one output parser to run multiqc. I think the challenge would be to ensure multiqc doesn't run prematurely. Also I don't think the TSO plugin can support multiple files?

**Comment by RachelDuffin** [comment]
Obsolete
